server:
    port: 8081
spring:
    application:
        name: userserivce
eureka:
    client:
        service-url:
            defaultZone: http://localhost:10086/eureka/
orderservice:
    ribbon:
        NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule